### ISSUE TITLE
Using in_array with third parameter explicitly set to false should be allowed

### ISSUE THREAD

**Issue by pamil** [phpstan/phpstan-strict-rules#1]
`in_array($needle, $haystack, false)` is a completely correct and explicit syntax when you do want to compare items by `==`.

**Comment by kubawerlos** [comment]
> This repository contains additional rules that revolve around strictly and strongly typed code with no loose casting

So no, using `in_array` in non-strict mode should not be allowed.

**Comment by ondrejmirtes** [comment]
You both have a point.

I think that a setting should be in place. By default, `false` is reported as an error, but one can turn off this behaviour.

**Comment by kubawerlos** [comment]
Setting is fine, as long as I don't have to use it. I expect to have an error when I miss the non-strict mode in `in_array` (both explicit and implicit) during code review.

I still stand with my opinion that `in_array` in non-strict mode implies there is something wrong with the code design.
