### ISSUE TITLE
Wrong type detection when using scalar as boolean

### ISSUE THREAD

**Issue by ossinkine** [phpstan/phpstan-strict-rules#104]
# Bug report

PHPStan wrongly detects variable type in if statement

### Code snippet that reproduces the problem

https://phpstan.org/r/eb86212e-623f-4153-8e29-74d952aa1692

### Expected output

Error is detected correctly, but message is wrong, I expect `Only booleans are allowed in &&, string given on the right side.`

**Comment by ossinkine** [comment]
Thank you for transferring the issue to the correct repository.

This issue isn't even related to casting scalar to boolean value, boolean variables are also detected wrongly
https://phpstan.org/r/00492471-9fd2-4a2d-9688-818f36f0698a

**Comment by ondrejmirtes** [comment]
Fixed: https://github.com/phpstan/phpstan-strict-rules/commit/f8207766a349d9fb76b06c9cee71ef68a24eb504
