### ISSUE TITLE
Create  0.12.0 version

### ISSUE THREAD

**Issue by steevanb** [phpstan/phpstan-strict-rules#106]
Can you create `0.12.0` version please?

We can't install `phpstan/phpstran-strict-rules 0.11.*` with `phpstan/phpstan 0.12.*`

**Comment by kubawerlos** [comment]
https://github.com/phpstan/phpstan-strict-rules/releases/tag/0.12.0

**Comment by ondrejmirtes** [comment]
You might have a typo in there: `phpstan/phpstran-strict-rules`

Anyway, feel free to post the message Composer shows to you.
