### ISSUE TITLE
Add flag to disable check docblock annotation for MissingFunctionParameterTypehintRule etc.

### ISSUE THREAD

**Issue by ZeinCube** [phpstan/phpstan-strict-rules#112]
I am using the latest version of your repository
In your phpstan ruleset I found such rules as 
MissingFunctionParameterTypehintRule
MissingFunctionReturnTypehintRule

But this rules also checks docblock annotations, not PHP-leveled type hints
I think these rules should have also flag or something like to check only native php type hints
How do I enable them for basic functions which have no native php type hints?

**Comment by ondrejmirtes** [comment]
Hi, your feature request isn't obvious, can you clarify more what you're asking and how should the behaviour change?

**Comment by ZeinCube** [comment]
I suggest that your parser can support strong typing at the language level without using annotations for type checking and typisation in general

**Comment by ondrejmirtes** [comment]
> I suggest that your parser can support strong typing at the language level

It does. Can you post an example on phpstan.org with expected vs. actual output?
