### ISSUE TITLE
strict-rules does not check operands of `and`

### ISSUE THREAD

**Issue by dktapps** [phpstan/phpstan-strict-rules#116]
# Bug report
I wasn't sure if this is a bug or missing feature, but it caused me to miss some bugs in my code, so here goes.

I imagine the same problem applies to `or` and `xor`, but I haven't checked this.

### Code snippet that reproduces the problem
Code using `and`: https://phpstan.org/r/b390269b-e5dd-4937-9703-05aa81763faf
Code using `&&`: https://phpstan.org/r/4574855e-a948-4924-bc5a-10c64891514f

### Expected output
The first sample should report the same errors as the second sample.

**Comment by ondrejmirtes** [comment]
Implemented (for bleedingEdge): https://github.com/phpstan/phpstan-strict-rules/commit/ee0009302ff5312ca6b92a7330a6b66da0c70f12
