### ISSUE TITLE
Prevent allowing direct call to __construct

### ISSUE THREAD

**Issue by DaveLiddament** [phpstan/phpstan-strict-rules#118]
# Feature request

I don't think code should be allowed to call `__construct` method. 

E.g. `$bob->__construct("Jane");`

https://phpstan.org/r/e261ee44-70c1-486b-958e-dc8abc1231d9

**Comment by canvural** [comment]
I guess this is now in PHPStan itself with [this](https://github.com/phpstan/phpstan-src/pull/1208) PR. 

https://phpstan.org/r/dd092672-9545-4e8c-804f-131178e27fb7

**Comment by ondrejmirtes** [comment]
Yes. It's gonna be in bleedingEdge in 1.6.0. Based on feedback I might move it to phpstan-strict-rules before 2.0 comes out.
