### ISSUE TITLE
forbid float values for json encoding

### ISSUE THREAD

**Issue by staabm** [phpstan/phpstan-strict-rules#122]
recently I was stumbling over problems, because of different php versions behave differently as far as encoding floats into json is a concern.

see https://3v4l.org/iekkW and this [conversation with nikita_ppv on twitter](https://twitter.com/markusstaab/status/1356980973544570885)

would it make sense to forbid floats in content which is passed to json_encode() in the context of phpstan-strict-rules?

**Comment by ondrejmirtes** [comment]
Nope.
