### ISSUE TITLE
`will always evaluate to true` in the constructor is not always true.

### ISSUE THREAD

**Issue by VincentLanglet** [phpstan/phpstan-strict-rules#129]
I have a class with the following code.
```
    /**
     * @var User
     */
    public $user;

public function __construct($options = null)
{
    parent::__construct($options);

    if (!$this->user instanceof User) {
        throw new InvalidArgumentException('The "user" parameter value is not valid.');
    }
}
```

The parent construct is the one from `Constraint` of Symfony, which is doing a lot of complicated things and setting class property from the `options`.

If a wrong options is passed, the user won't be set. So `this->user` can be `null|User` in the construct. 
In order to avoid checking the instance when I use the property, and because not passing the correct user option makes no sens for this class, I made a check directly in the construct right after I set the value (in the parent construct).

But this library is returning the error
```
Instanceof between AssuranceVie\Entity\User and AssuranceVie\Entity\User will always evaluate to true.
```

What would be the recommended way to fix this @ondrejmirtes ?

**Comment by ondrejmirtes** [comment]
You need to annotate your property with `@var User|null`. And access the instance with a private `getUser(): User` method that checks if the instance is present.
