### ISSUE TITLE
`will always evaluate to true` and tests

### ISSUE THREAD

**Issue by VincentLanglet** [phpstan/phpstan-strict-rules#130]
Let's say we have the following method 
```
function createDate(): \DateTime {
    return new \DateTime();
}
```
with the following phpunit test
```
self::assertInstanceOf(\DateTime::class, createDate());
```

Phpstan will return a `will always evaluate to true` error.

Without this test changing the code to 
```
function createDate(): ?\DateTime {
    return null;
}
```
won't break the CI

Of course I have real-case example more useful/complicated, for instance when returning an array `Foo[]`, the test can check that the objects inside the array are instance of `Foo` (even if the phpdoc is saying `Foo[]` tests should check this).

But the always true rule is useful is still useful in general.

What is the best way to fix this to you @ondrejmirtes ? I see two solutions
- Adding `will always evaluate to true` to the baseline for the tests directory. The issue is that every developer in my situation will have to do it ; and the plugin won't catch `always true` check in tests which are not assertion.
- Developping something in this plugin or in the phpstan-phpunit plugin in order to not throw an error when an assertion from phpunit is always true.

**Comment by ondrejmirtes** [comment]
What PHPStan recommends is to delete the unnecessary assert line:

```php
self::assertInstanceOf(\DateTime::class, createDate());
```

The assert doesn't do anything useful. If you're analysing the code you're testing with PHPStan (why shouldn't you) then you're already covered for errors like that and don't have to check them at runtime.

I don't want to change this behaviour because these PHPStan checks might make you realize "I wanted to assert something different" or "this test is completely useless".

**Comment by VincentLanglet** [comment]
> The assert doesn't do anything useful. If you're analysing the code you're testing with PHPStan (why shouldn't you) then you're already covered for errors like that and don't have to check them at runtime.

I'm not sure about this point.

If someone change the code to 
```
function createDate(): ?\DateTime {
    return null;
}
```
the tests won't fail if there is no test about the return type.

Another example:
```
/**
 * @return \DateTime[]
 */
function createDates(): array {
    return [new \DateTime(), new \DateTime()];
}
```
I could check that all the value are instance of \DateTime, because if someone change the code to
```
/**
 * @return \DateTimeImmutable[]
 */
function createDates(): array {
    return [new \DateTimeImmutable(), new \DateTimeImmutable()];
}
```
it won't fail too.

Phpstan is checking that the code is compatible with the phpdoc/types, but can't assert the code wont change.

But I'll go with the
```
            message: '#^Call to static method PHPUnit\\Framework\\Assert::.* will always evaluate to true\.$#'
            path: tests/
```
baseline. Just wanted to propose the idea.

**Comment by ondrejmirtes** [comment]
The question is - if someone changes the code intentionally and the change passes code review, why would you want to have a test fail?

Maybe you mean to use this package for that purpose? https://github.com/Roave/BackwardCompatibilityCheck
