### ISSUE TITLE
treatPhpDocTypesAsCertain query?

### ISSUE THREAD

**Issue by JaxkDev** [phpstan/phpstan-strict-rules#148]
I've now implemented phpstan-strict-rules in my project and disabled `treatPhpDocTypesAsCertain`, but I feel this scenario shouldn't be reported if that is disabled.
https://phpstan.org/r/f2832541-fff3-4d7e-a4e9-6e858aa98f02

locally produced with
phpstan: v1.3.0
phpstan-strict-rules: v1.1.0

**Comment by ondrejmirtes** [comment]
Works with this code :) https://phpstan.org/r/b20cb485-2617-4c4f-861f-53fc2ee190a7
