### ISSUE TITLE
Unable to use rules one-by-one when using extension-installer

### ISSUE THREAD

**Issue by nelson6e65** [phpstan/phpstan-strict-rules#150]
I follow [README documentation about this](https://github.com/phpstan/phpstan-strict-rules#enabling-rules-one-by-one), but it states that it is not compatible with the usage of https://github.com/phpstan/extension-installer.

There is a way to only use rules I want for the moment? Like levels?

**Comment by ondrejmirtes** [comment]
If you want to keep using extension-installer, the only way to have only some rules enabled is through ignoring errors: https://phpstan.org/user-guide/ignoring-errors

It'd be quite easy to make this more friendly, with the help of `conditionalTags` and custom parameters for each enabled rule. For someone fluent in the configuration (https://phpstan.org/developing-extensions/dependency-injection-configuration) it's a work for 30-60 minutes at most.

**Comment by nelson6e65** [comment]
> If you want to keep using extension-installer, the only way to have only some rules enabled is through ignoring errors: https://phpstan.org/user-guide/ignoring-errors

Thanks! I'll ignore some of these errors in my config file for the moment.

> It'd be quite easy to make this more friendly, with the help of `conditionalTags` and custom parameters for each enabled rule. For someone fluent in the configuration (https://phpstan.org/developing-extensions/dependency-injection-configuration) it's a work for 30-60 minutes at most.

🤔
