### ISSUE TITLE
Detect using deprecated elements

### ISSUE THREAD

**Issue by ondrejmirtes** [phpstan/phpstan-strict-rules#17]
Continuing work from https://github.com/phpstan/phpstan/pull/690... /cc @iluuu1994

- [ ] Extending deprecated class
- [ ] Implementing deprecated interface
- [ ] Using deprecated trait
- [ ] `new`ing deprecated class
- [ ] Accessing deprecated property
- [ ] Accessing deprecated static property
- [ ] Accessing static property on a deprecated class
- [ ] Accessing deprecated constant
- [ ] Accessing constant on a deprecated class
- [ ] Calling deprecated method
- [ ] Calling deprecated static method
- [ ] Calling static method on a deprecated class
- [ ] Calling deprecated function
- [ ] Overriding deprecated method (?)
- [ ] Typehinting deprecated class/interface (?) - in properties, method and function parameters, return typehints, in `@method` and `@property` annotations

Some of them are a little bit more obscure so I don't require all of them to exist right away, this is just a list of what I could think of.

**Comment by iluuu1994** [comment]
Here are my notes:

# PHPStan deprecations

- [x] Deprecated properties
- [x] Deprecated static properties
- [x] Deprecated classes
	- [x] When instantiating
	- [x] When inheriting
	- [x] When accessing static property
	- [x] When calling static method
- [x] Deprecated constants
- [x] Deprecated traits
- [x] Deprecated interfaces
- [x] ClassConstFetch

# Decisions

- Don't notify in deprecated class, method or function
- Don't notify on method call on deprecated classes
- Don't notify on property fetch call on deprecated classes
- Don't notify on class constant fetch of deprecated parent
- Don't notify on {self,static} constant calls on deprecated classes

**Comment by iluuu1994** [comment]
I'll have to check if the "Decisions" section is actually fully implemented. Something that is missing is not warning when using deprecated members in a deprecated scope (function or class). That should be a simple fix.

I'll create a pull request with those features ASAP. 

> Overriding deprecated method (?)

I was looking at how PHPStorm behaves in cases like these. Nothing is reported unless you actually specify again `@deprecated` in the overwritten method. This is up for debate, it's non-obvious for me what should happen in this case.

> Typehinting deprecated class/interface (?) - in properties, method and function parameters, return typehints, in @method and @property annotations

I'm not exactly sure what you mean here.

**Comment by ondrejmirtes** [comment]
> I'm not exactly sure what you mean here.

For example if you define a method and ask for a deprecated class in its typehint. You can do the same when defining properties or when defining annotation methods and properties (when the class implements `__call` or `__get`...).

**Comment by Majkl578** [comment]
As a further scope, would it be possible to extend this (reuse the logic) also to `@internal` and `@final` for example? Would be great! 😊

**Comment by iluuu1994** [comment]
Oh so you mean like:

```php
function nonDeprecatedFunction(): \DeprecatedFoo
{
}
```

We could do that but you'd most likely get a deprecation warning when instantiating it anyway. But yeah sure why not!

**Comment by iluuu1994** [comment]
@ondrejmirtes Yeah that's true. I'll see what I can do.

**Comment by iluuu1994** [comment]
@Majkl578 I will look into it.

**Comment by CZechBoY** [comment]
@iluuu1994 How is it going?

**Comment by iluuu1994** [comment]
@ondrejmirtes you can close this issue too 😄

**Comment by Majkl578** [comment]
How about this though?

> As a further scope, would it be possible to extend this (reuse the logic) also to `@internal` and `@final` for example? Would be great!

**Comment by iluuu1994** [comment]
I've been thinking about this. I need to extend the main repo first so that the PHPDoc attributes are properly parsed. It's a little unfortunate that all those flags are passed by hand to lots of functions which makes it hard to extend.

`@internal` is indeed very similar to `@deprecated`. `@final` only consists of a smaller subset of those rules though.

@ondrejmirtes Were would you prefer these rules to be?

**Comment by ondrejmirtes** [comment]
`@final` is obvious, but `@internal` is very tricky - what does it mean? What is an okay internal usage and what isn't?

As for where it'd be - don't know, could be another package 😀

**Comment by Majkl578** [comment]
> What is an okay internal usage and what isn't?

That should definitely be configurable somehow. :) At least by namespace. (So a library can use its own `@internal` classes, but not anyone else.)
