### ISSUE TITLE
Use of compersion operatore in some functions

### ISSUE THREAD

**Issue by StefanoTesla** [phpstan/phpstan-strict-rules#180]
Many days ago my code was:

```
        if (strpos($result, "\\n",0) > 0){

            $result = str_replace("\\n","",$result);

        }
```

Testing on PHPStan I get error on the `> 0` and at today I cannot replicate, but the error seggested to me that strpos can return 0 or false and the > 0 comparsion was not very good.

In the same day I tried olso:

```
        if (strpos($result, "\\n",0) <> false){

            $result = str_replace("\\n","",$result);

        }
```

And I didn't get any error but the right way is 

```
        if (strpos($result, "\\n",0) !== false){

            $result = str_replace("\\n","",$result);

        }
```

The most strange thing, is at today I cannot see the error message (I'm testing with the online editor)

**Comment by ondrejmirtes** [comment]
I don't think that these code snippets ever returned an error. `strpos` returns `int|false`.
