### ISSUE TITLE
Enforce https in the code

### ISSUE THREAD

**Issue by sylfabre** [phpstan/phpstan-strict-rules#181]
Hello

Would you accept a PR for a new rule looking for insecure links?

My idea is to search for `http:` in string nodes (PHPDoc, string variables, ...)

Have a nice day

**Comment by ondrejmirtes** [comment]
Hi, feel free to write a custom rule for this and even publish it as your own package, but this isn't a good fit for phpstan-strict-rules as it has little to do with type safety.

**Comment by sylfabre** [comment]
@ondrejmirtes Thank you for your feedback, it makes sense 👌 

If someone is looking for this rule, it's available at https://github.com/assoconnect/phpstan-rules
