### ISSUE TITLE
`noVariableVariables: false` does not disable some syntax of variable variables

### ISSUE THREAD

**Issue by mvorisek** [phpstan/phpstan-strict-rules#184]
config:
```
parameters:
    strictRules:
        noVariableVariables: false
```

does not disable some syntax of variable variables

demo: https://phpstan.org/r/1eca6f9f-708c-4ca9-a862-b8263765302f

in addition phpstan should never warn on `$this->{'v'}` (constant variable) - this is sometimes used to prevent PHP CS Fixer to prevent replacing of some phpunit methods - maybe it will get fixed by https://github.com/phpstan/phpstan/issues/7851

**Comment by ondrejmirtes** [comment]
Can you tell me what this attached code sample reports with `noVariableVariables: false`?

**Comment by ondrejmirtes** [comment]
Fixed by https://github.com/phpstan/phpstan-strict-rules/pull/186

**Comment by mvorisek** [comment]
> Can you tell me what this attached code sample reports with `noVariableVariables: false`?

I was about to provide some code demo... Thank you @ondrejmirtes and @MartinMystikJonas for fixing this quickly ❤️
