### ISSUE TITLE
`$this->{$key} = $val` is perfectly fine code

### ISSUE THREAD

**Issue by mvorisek** [phpstan/phpstan-strict-rules#187]
In data framework, we need to use `$this->{$key} = $val`.

What is wrong with this syntax? It is clearly readable and I belive there is no better replacement. If it is, please advise.

On the other side, `$$var` is definitely to be reported and very often a mistake. For the readability reasons, this example is often fixed to `${$var}` by common CS fixer. Demo: https://3v4l.org/0djPV

As long as variable variable uses the `${` syntax, I belive this is correct & well readable language construct and no error should be reported.

**Comment by ondrejmirtes** [comment]
Just turn it off if you disagree with the strict rule.

I believe you shouldn't use dynamic properties. A `private array $data` array would work the same way and it's much cleaner.

**Comment by mvorisek** [comment]
No, it is used correctly.

DI example: https://github.com/atk4/core/blob/f30d075208cd34127349e69eb6758f72e2deb9e4/src/DiContainerTrait.php#L58

such code is perfectly valid and strict rule is overly strict. As I pointed out, `$$var` should definitely emit an error, but `${$var}` should not be reported.

**Comment by ondrejmirtes** [comment]
@mvorisek We have a different opinion here. Also I'm politely asking you to be aware of my time constraints and to rate limit your questions and issues to a maximum of 1 per week.

if everyone had some many requests and questions, I'd need an army of people to keep up.

**Comment by hrach** [comment]
I'm politely asking to properly close issues as not planned and not as completed.

**Comment by ondrejmirtes** [comment]
Sorry, I don't care about GitHub's UI decision to create more mental burden on the maintainer. There used to be just one Close button and that's how I continue to see it.

**Comment by MartinMystikJonas** [comment]
@mvorisek If you want only certain syntax denied then it is job suited better for syntax analyser like CodeSniffer. You can disable variable variable checks in PHPStan or just add it to ignore in relevant places.

**Comment by MartinMystikJonas** [comment]
> @mvorisek If you want only certain syntax denied then it is job suited better for syntax analyser like CodeSniffer. You can disable variable variable checks in PHPStan or just add it to ignore in relevant places.

**Comment by dktapps** [comment]
You can't reliably prove that $object->{$var} is working code if you don't know what $var contains. The 3v4l sample is unrealistic because nobody is going to use that syntax if they knew at compile time which property they wanted to refer to.
