### ISSUE TITLE
Impl. `requireParentMethodCall`

### ISSUE THREAD

**Issue by mvorisek** [phpstan/phpstan-strict-rules#192]
This is a feature request to add a rule like `requireParentConstructorCall` to support all overriden methods.

demo: https://phpstan.org/r/854184e7-0d75-490a-843b-4f31f3ff06d6

most of the https://github.com/phpstan/phpstan-strict-rules/blob/1.4.x/src/Rules/Classes/RequireParentConstructCallRule.php code should be reusable

**Comment by dktapps** [comment]
I don't really see the use case. Many cases you'll have a good reason not to call the overridden method. I don't think a blanket rule like this makes any sense.

**Comment by mvorisek** [comment]
Good OOP design should call the less specific parent method. When parent method is not called, the parent impl. can broken easily. This is important to be detected especially when parent method was added after overridde method was introduced.

**Comment by ondrejmirtes** [comment]
phpstan-strict-rules are about opinionated code. But something that you need to configured isn't opinionated by default. You can definitely implement a custom rule for yourself 😊

My opinion in this matter is that inheritance causes more problems than it solves, and that composition and interfaces are much better.
