### ISSUE TITLE
False positive about possibly undefined variable after for loop

### ISSUE THREAD

**Issue by greg0ire** [phpstan/phpstan-strict-rules#195]
# Bug report

With strict rules turned on PHPStan reports that a variable will always be overwritten if followed by a `for` loop that uses it in the assignment part, and that's great: https://phpstan.org/r/244ed1d0-003c-492f-99d2-ce5a075ae515

If you attempt to fix that though, you run into a contradictory error:

### Code snippet that reproduces the problem

https://phpstan.org/r/030872ba-acba-4a27-b267-1f30156b1417

### Expected output

No errors

### Did PHPStan help you today? Did it make you happy in any way?

Yes, it helps me make it easier to spot errors in data providers

**Comment by MartinMystikJonas** [comment]
This is expected. Strict rules disallow use of variables from loops outside loops. You can turn off this behaviour (enabled by strict rules) by this config option https://phpstan.org/config-reference#pollutescopewithloopinitialassignments to ~~false~~ true (edited)

**Comment by greg0ire** [comment]
Thanks @MartinMystikJonas !
