### ISSUE TITLE
allRules parameters set to false do not turn off rules

### ISSUE THREAD

**Issue by ghost** [phpstan/phpstan-strict-rules#196]
Given this config
```neon
includes:
    - vendor/phpstan/phpstan-strict-rules/rules.neon

parameters:
    strictRules:
	allRules: false
```
and this code
```php
$a = 1;
if ($a === 1) {
}
```
I still get an error `Strict comparison using === between 1 and 1 will always evaluate to true.`

**Comment by ondrejmirtes** [comment]
See https://github.com/phpstan/phpstan-strict-rules/issues/185#issuecomment-1227365019
