### ISSUE TITLE
Force `@return` to match return type

### ISSUE THREAD

**Issue by tillkruss** [phpstan/phpstan-strict-rules#202]
Would this package allow us to force `@return` to match the native return type? `level: max` does not.

<img width="991" alt="Screenshot 2023-02-03 at 9 28 23 AM" src="https://user-images.githubusercontent.com/665029/216672877-8db4a66f-91e1-4713-bd8a-7e7300700ea7.png">

**Comment by ondrejmirtes** [comment]
No, but you can write a custom rule for that.
