### ISSUE TITLE
Add `uselessTrim` rule for useless `trim()`

### ISSUE THREAD

**Issue by mvorisek** [phpstan/phpstan-strict-rules#220]
This is a feature request to add `uselessTrim` like there is `uselessCast`.

repro: https://phpstan.org/r/daf97ab2-6a1b-4d54-a48e-d7503026c1c8

It should be possible for `numeric-string`, `empty-string` and known const strings.

**Comment by VincentLanglet** [comment]
> It should be possible for `numeric-string`

I don't think so, since `\is_numeric(' 0 ')` is true, but this value is trimmable.

**Comment by ondrejmirtes** [comment]
We can't do this unless we introduce new `trimmed-string` type. It's not worth it.
