### ISSUE TITLE
Relaxed booleansInConditions to allow 0, 1?

### ISSUE THREAD

**Issue by Alkarex** [phpstan/phpstan-strict-rules#221]
Hello,
While the `booleansInConditions` rule is nice in many situations, it does not work so elegantly with functions returning near-booleans { 0, 1 }.
A salient example is [`preg_match()`](https://php.net/function.preg-match):

> preg_match() returns 1 if the pattern matches given subject, 0 if it does not, or false on failure. 

Would you have a suggestion to relax `booleansInConditions` to { false, true, 0, 1} with the current code-base?
If not, would you welcome a PR to allow this possibility? (And if so, hints welcome)

**Comment by ColonelMoutarde** [comment]
See --> https://github.com/FreshRSS/FreshRSS/pull/5501#issuecomment-1621427534

**Comment by ondrejmirtes** [comment]
I disagree. It returns `0|1|false`, and you should be interested in the difference between `0` and `false`.

**Comment by ondrejmirtes** [comment]
You can always disable this rule in phpstan-strict-rules, and write your own :)

**Comment by Alkarex** [comment]
> You can always disable this rule in phpstan-strict-rules, and write your own

That is not answering the question, but then I am guessing that you are not interested in a PR to add a rule to check for "relaxed booleans in conditions". Let me know otherwise.

**Comment by ondrejmirtes** [comment]
> I am guessing that you are not interested in a PR to add a rule

No, I'm not, I have a different opinion.
