### ISSUE TITLE
Cannot recognize property type when using traits inside traits

### ISSUE THREAD

**Issue by emodric** [phpstan/phpstan-strict-rules#24]
I'm not sure if this is an issue with PHPStan or strict rules, but it kicks in only when using strict rules.

```
trait Foo
{
    /**
     * @var string
     */
    protected $foo;
}

trait Bar
{
    use Foo;
}

class Baz
{
    use Bar;
}
```

results in:

```
 ------ ---------------------------------------------- 
  Line   src/Foo.php (in context of class Baz)         
 ------ ---------------------------------------------- 
  8      Property Baz::$foo has no typehint specified  
 ------ ---------------------------------------------- 
```

**Comment by ondrejmirtes** [comment]
Hi, are you using the latest dev-master of both phpstan/phpstan and strict-rules?

**Comment by emodric** [comment]
Yep, both are on latest `dev-master`.

**Comment by ondrejmirtes** [comment]
OK, looks like that if you directly use a trait by a class, the issue is gone, but if you have a chain class-trait-trait, the typehint is not seen. Will look into it, thanks!

**Comment by emodric** [comment]
Yep, sorry, failed to mention that it works when using the trait directly :)

**Comment by ondrejmirtes** [comment]
Fixed: https://github.com/phpstan/phpstan/commit/5889640ff053e705abe881ab92c117c8304661f7
