### ISSUE TITLE
False positive "Variable might not be defined" after `for` loop

### ISSUE THREAD

**Issue by Wirone** [phpstan/phpstan-strict-rules#242]
I believe strict rules falsely report [this](https://phpstan.org/r/b54ba230-2e05-4be8-930b-58f9190acde7). Assignment is always done, and then condition is checked so it can escape the loop early, but `$i` is there, right? [This is the fix](https://phpstan.org/r/3465b364-00a8-4024-9c91-afbac8ecbee4), but it does not look good to move initial assignments before the for loop.

**Comment by ondrejmirtes** [comment]
This is a feature, not a bug of strict-rules. You can turn it off with this setting https://phpstan.org/config-reference#pollutescopewithloopinitialassignments

phpstan-strict-rules mimics how other stricter languages act with loop-scoped variables.
