### ISSUE TITLE
Bug: disallowedShortTernary can not be disabled

### ISSUE THREAD

**Issue by dbu** [phpstan/phpstan-strict-rules#248]
rules can be individually disabled, but disallowedShortTernary is not in the configuration and can therefore not be disabled.

workaround in project phpstan.neon configuration file:

```
parameters:
    ignoreErrors:
        - identifier: ternary.shortNotAllowed
```

**Comment by ruudk** [comment]
Fixed in https://github.com/phpstan/phpstan-strict-rules/pull/249

**Comment by dbu** [comment]
wow, that was quick! thanks a lot!
