### ISSUE TITLE
MissingPropertyTypehintRule: false positive with cache

### ISSUE THREAD

**Issue by klapuch** [phpstan/phpstan-strict-rules#50]
Steps to reproduce:
1. Create trait with property, but with missing `@var` annotation.
2. Use it in some class
3. Run phpstan - it should warn that the property has no typehint specified
4. Add `@var` annotation
5. Run phpstan again
6. It still shows, that property has no typehint specified
7. Clear cache

**Comment by ondrejmirtes** [comment]
Duplicate of https://github.com/phpstan/phpstan/issues/1601
