### ISSUE TITLE
Specifying a type hint for a resource parameter prevents it of being validated

### ISSUE THREAD

**Issue by marcospassos** [phpstan/phpstan-strict-rules#53]
Specifying a type hint for a resource parameter prevents it of being validated, as demonstrated in
https://phpstan.org/r/3353e83f-f844-4f24-a68f-f3e2ebb704eb

**Comment by ondrejmirtes** [comment]
That’s a feature, you don’t have to check it.

**Comment by marcospassos** [comment]
If I want to, it should be possible, right?

```php
/** @var mixed $value **/
if (!\is_resource($value)) {
    throw new \InvalidArgumentException('Not a resource.');
}
```

https://phpstan.org/r/a0f724ba-3a0b-482a-bd34-aad29329cf5a

**Comment by ondrejmirtes** [comment]
If you really want your code to look like this https://phpstan.org/r/3353e83f-f844-4f24-a68f-f3e2ebb704eb, you should just use `ignoreErrors`.
