### ISSUE TITLE
Rule Request: Check that list not dictionary is returned

### ISSUE THREAD

**Issue by CZechBoY** [phpstan/phpstan-strict-rules#58]
So https://phpstan.org/r/bce64dd4-7b61-4255-97e0-212d45563beb should report error that `array<string, callable>` is returned instead of `callable[]`.

**Comment by ondrejmirtes** [comment]
I don't get it. `@return callable[]` is correct.

**Comment by ondrejmirtes** [comment]
Because that's `array<int|string, callable>`.

**Comment by CZechBoY** [comment]
So then every php array is list?

**Comment by ondrejmirtes** [comment]
`callable[]` means any array, both list and dictionary. I don't want to force the `array<>` syntax on people right now... But you're welcome to write the rule on your own, should be easy.

**Comment by CZechBoY** [comment]
Is there any easy way/parameter to change this behavior? Or should I write my own rule for this specific scenario?

**Comment by ondrejmirtes** [comment]
You should write your own rule.
