### ISSUE TITLE
Explode & wrong error: Call to function is_array() with array<int, string> will always evaluate to true

### ISSUE THREAD

**Issue by vlobovikov** [phpstan/phpstan-strict-rules#69]
Function "explode" return a array or false value. [https://secure.php.net/manual/en/function.explode.php](manual)

`$a = explode($separator, $array);
if (\is_array($a)) {
...
}`

error message: "Call to function is_array() with array<int, string> will always evaluate to true."

Phpstan Version: 0.11.1

**Comment by vlobovikov** [comment]
in phpstan.org: https://phpstan.org/r/5d6e8557-1ca9-4293-af0d-c56f617b77a9
I get only one error: "Result of && is always true."

**Comment by ondrejmirtes** [comment]
I challenge you to produce "not ok": https://3v4l.org/U8SJ7

**Comment by vlobovikov** [comment]
here - https://3v4l.org/ecfEs

**Comment by ondrejmirtes** [comment]
PHPStan also tells you that: https://phpstan.org/r/92b6e91f-7212-4eb2-8ed2-ec5ec8a3c8c3 So I don't see a bug here.

**Comment by vlobovikov** [comment]
for exp.:  we get the separator from any function and the separator have empty string. We must verify "\is_array($texts) && \is_array($texts2)"

`
$separator = '';
$array = 'this is, a test';
$array2 = 'this is, a test2';
$texts = explode($separator, $array);
$texts2 = explode($separator, $array2);

if (\is_array($texts) && \is_array($texts2)){
	echo 'ok';
} else {
    echo 'not ok';
}`

`
public function test(string $separator)
 $array = 'this is, a test';
 $array2 = 'this is, a test2';
 $texts = explode($separator, $array);
 $texts2 = explode($separator, $array2);

 if (\is_array($texts) && \is_array($texts2)){
	echo 'ok';
 } else {
    echo 'not ok';
 }

}
`

**Comment by ondrejmirtes** [comment]
I can't reproduce it: https://phpstan.org/r/3aa1b88b-1278-461b-b66b-48267f5b1dc4

**Comment by vlobovikov** [comment]
https://phpstan.org/r/39771324-41ee-4ef1-aa9f-65c900b5f55c

**Comment by ondrejmirtes** [comment]
https://3v4l.org/ecfEs

We're not making any progress here. Unless you produce an example that shows "not ok" on 3v4l.org and "No errors" on phpstan.org, there's no bug.

**Comment by vlobovikov** [comment]
https://3v4l.org/ecfEs - "not ok"

https://phpstan.org/r/39771324-41ee-4ef1-aa9f-65c900b5f55c 


> +------------------------------------------------------------------------------+
| Line | test.php                                                              |
+------------------------------------------------------------------------------+
| 9    | Result of && is always false.                                 |
| 9    | Call to function is_array() with false will always evaluate to false. |
| 9    | Call to function is_array() with false will always evaluate to false. |
+------------------------------------------------------------------------------+

**Comment by ondrejmirtes** [comment]
Yes, PHPStan tells you actually what's going on. It can differentiate between empty  (`false`), non-empty (`array<string>`) and unknown `(`array<string>|false`) delimiter.
