### ISSUE TITLE
False positive: Call to function assert() with bool will always evaluate to true

### ISSUE THREAD

**Issue by enumag** [phpstan/phpstan-strict-rules#74]
https://phpstan.org/r/33f4a31d-1316-463d-b7aa-6978623175de

Expected result: no error

**Comment by enumag** [comment]
@ondrejmirtes @localheinz Any idea what's causing this false positive?

**Comment by ondrejmirtes** [comment]
No, but feel free to investigate.

**Comment by ondrejmirtes** [comment]
It will be somewhere in ImpossibleCheckTypeHelper.

**Comment by enumag** [comment]
Fixed by https://github.com/phpstan/phpstan-src/commit/ca044c40c30fdfa01bbca75f816c82c63aff3448
