### ISSUE TITLE
Disallow usage of ISO8601 constants

### ISSUE THREAD

**Issue by villermen** [phpstan/phpstan-strict-rules#79]
I have created a custom rule that disallows use of `\DateTimeInterface::ISO8601` and `\DATE_ISO8601` constants because they are not actually ISO 8601 compatible (ATOM is). It's a common pitfall and I wanted to prevent it from happening again in my team.

I could cook up a PR for this repository in a matter of minutes. Would that be appreciated or does the rule not really fit in with this repository's idealogy?

https://www.php.net/manual/en/class.datetimeinterface.php#datetime.constants.iso8601

**Comment by ondrejmirtes** [comment]
Hi, this is too opinionated case for a rule. Feel free to implement it for your own team, but it's not a good fit for PHPStan core, because someone might use this constant on purpose.
