### ISSUE TITLE
"Property has no typehint specified" when it has native type (PHP 7.4)

### ISSUE THREAD

**Issue by kocsismate** [phpstan/phpstan-strict-rules#82]
Hi there,

My issue is that for 

```
class A
{
    private string $b;
}
```

I get the following error:

`Property A::$b has no typehint specified.`

PHPStan should recognize the native type of the property instead of only using the PHPDoc type.

**Comment by ondrejmirtes** [comment]
Hi, PHP 7.4 hasn't been released yet. Support for PHP 7.4 is coming. I'm waiting until feature freeze to implement these features.

**Comment by kocsismate** [comment]
Thanks for the quick feedback! I couldn't resist not to try out the current alpha version, but found a couple of issues with tooling (PHPStan and PHP CS), so I'll wait a couple of weeks. :)

**Comment by kocsismate** [comment]
Thanks for releasing PHPStan 0.11.13. I am closing the ticket.
