### ISSUE TITLE
Instanceof between Doctrine collections and array of entities

### ISSUE THREAD

**Issue by ikvasnica** [phpstan/phpstan-strict-rules#96]
Hi,

I might have found a bug when using the `instanceof` with Doctrine collections and entities.

**Code example:**
```
    use Doctrine\Common\Collections\ArrayCollection;
    use App\Entity\TextEntity;

    /**
     * @param TextEntityList|TextEntity[]|ArrayCollection $text
     */
    public function setText($text): void
    {
        if ($text instanceof TextEntityList) { // just a regular object
            $this->text = new ArrayCollection($text->getArrayValues());
        } elseif ($text instanceof ArrayCollection) {
            $this->text = $text;
        } else { // this should happen only when $text is an array of TextEntity (which is a standard Doctrine entity object)
            $this->text = new ArrayCollection($text);
        }
    }
```

PHPStan Strict Rules evaluates this code with the following error:
`Instanceof between Doctrine\\Common\\Collections\\ArrayCollection&iterable<App\Entity\TextEntity> and Doctrine\\Common\\Collections\\ArrayCollection will always evaluate to true`

In reality, **PHP does not evaluate this condition as always true** and the `else` branch is, in fact, reachable.

Is there any solution I am missing or is it a bug? 

Thank you.

**Comment by ondrejmirtes** [comment]
`TextEntity[]|ArrayCollection` is interpreted as "ArrayCollection of TextEntity". That's a feature.

If you mean "ArrayCollection of TextEntity OR an array of TextEntity", use something like this:

```
array<TextEntity>|ArrayCollection<TextEntity>
```
