### ISSUE TITLE
Report for loops overwriting variables from parent scope (a la foreach)

### ISSUE THREAD

**Issue by dktapps** [phpstan/phpstan-strict-rules#98]
https://phpstan.org/r/8f361ed5-7e15-4ffc-a6b0-3b5c33a3b419

PhpStorm complains about code like this, because an argument is being overwritten by a loop, which might not be intended behaviour.

I found it strange that overwriting from `foreach` context is reported, but not from `for` context.

Is there a reason for this not being reported, or just a missing feature?

**Comment by ondrejmirtes** [comment]
Can you post an expected output?

**Comment by dktapps** [comment]
I'd expect an error to be reported from line `7`, telling that the `for` loop is overwriting the var `$a`.

**Comment by ondrejmirtes** [comment]
No problem, get inspired: https://github.com/phpstan/phpstan-strict-rules/blob/master/src/Rules/ForeachLoop/OverwriteVariablesWithForeachRule.php

**Comment by dktapps** [comment]
`For loop initial assignment overwrites variable $a` seems clear enough, I think.

I could create a PR to implement this if it's desirable.

**Comment by ondrejmirtes** [comment]
Yes 😊
